namespace Cu1uSFX
{
    // [Cu1uSFX]
    // DO NOT EDIT - this file is automatically generated by SFXEnumGenerator as you define sounds in the SFX List asset. Changes made here will be overwritten.
    // DO NOT MOVE THIS FILE - A new one will be generated. Instead, change the location of this script by assigning a new target in the SFX List in /Assets/Resources/SFX List
    public static class SFX
    {
    }
}
